resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/jeffellin/gateway.git
    branch: master
jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: hello-world
    file: resource-tutorial/ci/hello-world.yml


